version: '3.9'
services:
  mongodb:
    image: mongo:7
    container_name: mongodb_backend_vocab
    ports:
      - 27017:27017
    environment:
      # - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=bono
      - MONGO_INITDB_ROOT_PASSWORD=ngoc25
    # volumes:
    #   - mongodb-data:/data/db

  app-backend:
    depends_on:
      - mongodb
    container_name: app_backend_vocab
    build: .
    ports:
      - '4030:4030'
    environment:
      - NODE_ENV=development
    # volumes:
    #   - .:/app
    command: npm start
