version: '3.9'
services:
  app-backend:
    # depends_on:
    #   - mongodb
    container_name: app_backend_vocab
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${LOCAL_PORT}:${LOCAL_PORT}'
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DOCKER_MONGO_URL: ${DOCKER_MONGO_URL}
    restart: unless-stopped
# No need use mongodb because we use mongo atlas available
# mongodb:
#   image: mongo:7
#   container_name: mongodb_vocab
#   ports:
#     - 27019:27017
#   env_file:
#     - .env
