version: '3.9'
services:
  app-backend:
    depends_on:
      - mongodb
    container_name: app_backend_vocab
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${LOCAL_PORT}:${LOCAL_PORT}'
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: mongodb_vocab
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
