name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Build the Docker image
        run: docker build -t ngocxxu/vocab-management:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image to Docker Hub
        run: docker push ngocxxu/vocab-management:latest

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: '${{ secrets.KOYEB_TOKEN }}'
      - name: Deploy to Koyeb
        run: koyeb service redeploy server/vocab-management
